// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmhzrfbfuvjmtrifwffy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtaHpyZmJmdXZqbXRyaWZ3ZmZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDQ5ODgsImV4cCI6MjA2MzU4MDk4OH0.QK88YyBoxS9gIzUcXe9GDmpnUuSk_ITvdWU5htuBdZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

export type Chat = Database['public']['Tables']['chats']['Row'];
export type Message = Database['public']['Tables']['messages']['Row'];